# Generated by Django 4.2.10 on 2025-05-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_notification_options_notification_post_and_more'),
        ('blog', '0002_fix_email_address_user_fk'),
    ]

    operations = [
    ]
