# Generated by Django 4.2.10 on 2025-06-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reacts',
            name='react',
            field=models.CharField(choices=[('Love', 'Love'), ('Dislike', 'Dislike'), ('Thunder', 'Thunder')], max_length=10),
        ),
    ]
