# Generated by Django 4.2.10 on 2025-07-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_fix_admin_log_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='toolkit_tokens',
            field=models.PositiveIntegerField(default=50, help_text='Number of toolkit tokens available to the user'),
        ),
    ]
